spring:
 datasource:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: hdelaluza 
      password: 123456 
      driver-class-name: oracle.jdbc.OracleDriver
 jpa:
   hibernate:
     naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl		
server:
    port: 10000
#Config de el servicio de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka	
